version: "3.8"
services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    environment:
      NODE_ENV: production
        
  #docker-compose up -d
  #mappings file should be same line to avoid  mapping error
  #docker-compose down
